/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosotrosRouteImport } from './routes/sobre-nosotros'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as EjemploInformeRouteImport } from './routes/ejemplo-informe'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ConsultarCitaRouteImport } from './routes/consultar-cita'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ClasicoRouteImport } from './routes/clasico'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalleresIndexRouteImport } from './routes/talleres.index'
import { Route as ReservarIndexRouteImport } from './routes/reservar.index'
import { Route as TalleresLoginRouteImport } from './routes/talleres.login'
import { Route as TalleresDashboardRouteImport } from './routes/talleres.dashboard'
import { Route as ReservarConfirmacionRouteImport } from './routes/reservar.confirmacion'
import { Route as LegalTerminosRouteImport } from './routes/legal.terminos'
import { Route as LegalPrivacidadRouteImport } from './routes/legal.privacidad'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalAvisoLegalRouteImport } from './routes/legal.aviso-legal'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as TalleresInspeccionIdRouteImport } from './routes/talleres.inspeccion.$id'

const SobreNosotrosRoute = SobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const EjemploInformeRoute = EjemploInformeRouteImport.update({
  id: '/ejemplo-informe',
  path: '/ejemplo-informe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultarCitaRoute = ConsultarCitaRouteImport.update({
  id: '/consultar-cita',
  path: '/consultar-cita',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasicoRoute = ClasicoRouteImport.update({
  id: '/clasico',
  path: '/clasico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalleresIndexRoute = TalleresIndexRouteImport.update({
  id: '/talleres/',
  path: '/talleres/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarIndexRoute = ReservarIndexRouteImport.update({
  id: '/reservar/',
  path: '/reservar/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalleresLoginRoute = TalleresLoginRouteImport.update({
  id: '/talleres/login',
  path: '/talleres/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TalleresDashboardRoute = TalleresDashboardRouteImport.update({
  id: '/talleres/dashboard',
  path: '/talleres/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservarConfirmacionRoute = ReservarConfirmacionRouteImport.update({
  id: '/reservar/confirmacion',
  path: '/reservar/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTerminosRoute = LegalTerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const LegalAvisoLegalRoute = LegalAvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => LegalRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TalleresInspeccionIdRoute = TalleresInspeccionIdRouteImport.update({
  id: '/talleres/inspeccion/$id',
  path: '/talleres/inspeccion/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clasico': typeof ClasicoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/consultar-cita': typeof ConsultarCitaRoute
  '/contacto': typeof ContactoRoute
  '/ejemplo-informe': typeof EjemploInformeRoute
  '/legal': typeof LegalRouteWithChildren
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/reservar/confirmacion': typeof ReservarConfirmacionRoute
  '/talleres/dashboard': typeof TalleresDashboardRoute
  '/talleres/login': typeof TalleresLoginRoute
  '/reservar/': typeof ReservarIndexRoute
  '/talleres/': typeof TalleresIndexRoute
  '/talleres/inspeccion/$id': typeof TalleresInspeccionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clasico': typeof ClasicoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/consultar-cita': typeof ConsultarCitaRoute
  '/contacto': typeof ContactoRoute
  '/ejemplo-informe': typeof EjemploInformeRoute
  '/legal': typeof LegalRouteWithChildren
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/reservar/confirmacion': typeof ReservarConfirmacionRoute
  '/talleres/dashboard': typeof TalleresDashboardRoute
  '/talleres/login': typeof TalleresLoginRoute
  '/reservar': typeof ReservarIndexRoute
  '/talleres': typeof TalleresIndexRoute
  '/talleres/inspeccion/$id': typeof TalleresInspeccionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clasico': typeof ClasicoRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/consultar-cita': typeof ConsultarCitaRoute
  '/contacto': typeof ContactoRoute
  '/ejemplo-informe': typeof EjemploInformeRoute
  '/legal': typeof LegalRouteWithChildren
  '/sobre-nosotros': typeof SobreNosotrosRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/legal/aviso-legal': typeof LegalAvisoLegalRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/reservar/confirmacion': typeof ReservarConfirmacionRoute
  '/talleres/dashboard': typeof TalleresDashboardRoute
  '/talleres/login': typeof TalleresLoginRoute
  '/reservar/': typeof ReservarIndexRoute
  '/talleres/': typeof TalleresIndexRoute
  '/talleres/inspeccion/$id': typeof TalleresInspeccionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clasico'
    | '/como-funciona'
    | '/consultar-cita'
    | '/contacto'
    | '/ejemplo-informe'
    | '/legal'
    | '/sobre-nosotros'
    | '/admin/dashboard'
    | '/admin/login'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/reservar/confirmacion'
    | '/talleres/dashboard'
    | '/talleres/login'
    | '/reservar/'
    | '/talleres/'
    | '/talleres/inspeccion/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clasico'
    | '/como-funciona'
    | '/consultar-cita'
    | '/contacto'
    | '/ejemplo-informe'
    | '/legal'
    | '/sobre-nosotros'
    | '/admin/dashboard'
    | '/admin/login'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/reservar/confirmacion'
    | '/talleres/dashboard'
    | '/talleres/login'
    | '/reservar'
    | '/talleres'
    | '/talleres/inspeccion/$id'
  id:
    | '__root__'
    | '/'
    | '/clasico'
    | '/como-funciona'
    | '/consultar-cita'
    | '/contacto'
    | '/ejemplo-informe'
    | '/legal'
    | '/sobre-nosotros'
    | '/admin/dashboard'
    | '/admin/login'
    | '/legal/aviso-legal'
    | '/legal/cookies'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/reservar/confirmacion'
    | '/talleres/dashboard'
    | '/talleres/login'
    | '/reservar/'
    | '/talleres/'
    | '/talleres/inspeccion/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClasicoRoute: typeof ClasicoRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ConsultarCitaRoute: typeof ConsultarCitaRoute
  ContactoRoute: typeof ContactoRoute
  EjemploInformeRoute: typeof EjemploInformeRoute
  LegalRoute: typeof LegalRouteWithChildren
  SobreNosotrosRoute: typeof SobreNosotrosRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ReservarConfirmacionRoute: typeof ReservarConfirmacionRoute
  TalleresDashboardRoute: typeof TalleresDashboardRoute
  TalleresLoginRoute: typeof TalleresLoginRoute
  ReservarIndexRoute: typeof ReservarIndexRoute
  TalleresIndexRoute: typeof TalleresIndexRoute
  TalleresInspeccionIdRoute: typeof TalleresInspeccionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nosotros': {
      id: '/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/sobre-nosotros'
      preLoaderRoute: typeof SobreNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ejemplo-informe': {
      id: '/ejemplo-informe'
      path: '/ejemplo-informe'
      fullPath: '/ejemplo-informe'
      preLoaderRoute: typeof EjemploInformeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultar-cita': {
      id: '/consultar-cita'
      path: '/consultar-cita'
      fullPath: '/consultar-cita'
      preLoaderRoute: typeof ConsultarCitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clasico': {
      id: '/clasico'
      path: '/clasico'
      fullPath: '/clasico'
      preLoaderRoute: typeof ClasicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talleres/': {
      id: '/talleres/'
      path: '/talleres'
      fullPath: '/talleres/'
      preLoaderRoute: typeof TalleresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar/': {
      id: '/reservar/'
      path: '/reservar'
      fullPath: '/reservar/'
      preLoaderRoute: typeof ReservarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talleres/login': {
      id: '/talleres/login'
      path: '/talleres/login'
      fullPath: '/talleres/login'
      preLoaderRoute: typeof TalleresLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talleres/dashboard': {
      id: '/talleres/dashboard'
      path: '/talleres/dashboard'
      fullPath: '/talleres/dashboard'
      preLoaderRoute: typeof TalleresDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservar/confirmacion': {
      id: '/reservar/confirmacion'
      path: '/reservar/confirmacion'
      fullPath: '/reservar/confirmacion'
      preLoaderRoute: typeof ReservarConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terminos': {
      id: '/legal/terminos'
      path: '/terminos'
      fullPath: '/legal/terminos'
      preLoaderRoute: typeof LegalTerminosRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/aviso-legal': {
      id: '/legal/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/legal/aviso-legal'
      preLoaderRoute: typeof LegalAvisoLegalRouteImport
      parentRoute: typeof LegalRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talleres/inspeccion/$id': {
      id: '/talleres/inspeccion/$id'
      path: '/talleres/inspeccion/$id'
      fullPath: '/talleres/inspeccion/$id'
      preLoaderRoute: typeof TalleresInspeccionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LegalRouteChildren {
  LegalAvisoLegalRoute: typeof LegalAvisoLegalRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
  LegalTerminosRoute: typeof LegalTerminosRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalAvisoLegalRoute: LegalAvisoLegalRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
  LegalTerminosRoute: LegalTerminosRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClasicoRoute: ClasicoRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ConsultarCitaRoute: ConsultarCitaRoute,
  ContactoRoute: ContactoRoute,
  EjemploInformeRoute: EjemploInformeRoute,
  LegalRoute: LegalRouteWithChildren,
  SobreNosotrosRoute: SobreNosotrosRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  ReservarConfirmacionRoute: ReservarConfirmacionRoute,
  TalleresDashboardRoute: TalleresDashboardRoute,
  TalleresLoginRoute: TalleresLoginRoute,
  ReservarIndexRoute: ReservarIndexRoute,
  TalleresIndexRoute: TalleresIndexRoute,
  TalleresInspeccionIdRoute: TalleresInspeccionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
